---
dg-publish: true
permalink: "/docker/issues/docker-container-\rexternal communication-issue/"
dgPassFrontmatter: true
---
### 💡 도커 컨테이너의 외부 통신 이슈

-   jdk 문제부터, COPY 시, 경로 문제까지 여러 이슈들이 있었지만 따로 캡처를 하지 못했다. 어쨌든 해결을 하고 빌드가 성공적으로 되자, 설레는 마음으로 컨테이너를 실행 시켜봤다. 하지만 바로 실행이 종료됐다. 로그를 봐 보니, 분명 로컬에서 그냥 실행할 때는 잘 됐던 DB 연결에 문제가 생겼다.  
    
    ![](https://i.imgur.com/PRRp4LN.png)
    
-   해당 이슈를 검색하던 중, DB는 아니었지만 웹 페이지 요청에서 비슷한 이슈를 보았다.([\[Docker\] 도커 컨테이너 외부 통신: host.docker.internal (tistory.com)](https://da2uns2.tistory.com/entry/Docker-%EB%8F%84%EC%BB%A4-%EC%BB%A8%ED%85%8C%EC%9D%B4%EB%84%88-%EC%99%B8%EB%B6%80-%ED%86%B5%EC%8B%A0)) mariaDB는 내 PC(HOST PC)에서 작동 중이었고, 컨테이너에서 build되는 서버 프로그램은 application.yml 을 통해 host PC에서 동작 중인 DB와 연결하도록 설정했기 때문이었다.
-   아래 처럼 작성된 코드에서 localhost -> host.docker.internal로 변경해주면 해결된다.  
    
    ![](https://i.imgur.com/wmZfTQ9.png)
    
    ![](https://i.imgur.com/WuBevAn.png)
    
-   정상적으로 실행되고, DDL -AUTO옵션까지 잘 실행해 주는 모습이다.
-   ![](https://i.imgur.com/nXafzcX.png)
    
-   Post man 으로 회원 가입 요청을 보낸 모습이다.  
    
    ![](https://i.imgur.com/fgGgvIM.png)